import type { Product } from "@/types";

export const PRODUCTS: Product[] = [
  // ── Printers & MFP ──────────────────────────────────────────────────────────
  {
    id: "dcp-t730dw",
    name: "DCP-T730DW Brother Ink Tank 3-in-1 A4 Color Printer",
    slug: "dcp-t730dw",
    categorySlug: "printers-mfp",
    categoryName: "Printers & MFP",
    brand: "Brother",
    price: 70.0,
    description:
      "Versatile 3-in-1 inkjet printer with print, scan and copy capabilities. Features Wi-Fi, duplex printing and a 20-sheet ADF for efficient document handling.",
    specs: [
      { label: "Functions", value: "Print, Scan, Copy" },
      { label: "Print Speed", value: "Up to 16/9 ipm (Mono/Colour)" },
      { label: "Print Resolution", value: "Up to 1,200 x 6,000 dpi" },
      { label: "ADF Capacity", value: "20 Sheets" },
      { label: "Paper Tray", value: "150 Sheets A4" },
      { label: "Duplex", value: "Yes" },
      { label: "Connectivity", value: "USB 2.0, Wireless, Wi-Fi Direct" },
      { label: "Display", value: "1-Line LCD (16 characters)" },
      { label: "Memory", value: "128 MB" },
      { label: "Mobile Printing", value: "AirPrint, Mopria" },
      { label: "Dimensions (WxDxH)", value: "390 × 343 × 182.5 mm" },
    ],
    isFeatured: true,
    isNew: true,
    inStock: true,
    images: ["/products/dcp-t730dw.jpg"],
  },
  {
    id: "mfc-t930dw",
    name: "MFC-T930DW Brother 4-in-1 Ink Tank A4 Multifunction Printer",
    slug: "mfc-t930dw",
    categorySlug: "printers-mfp",
    categoryName: "Printers & MFP",
    brand: "Brother",
    price: 105.0,
    description:
      "Advanced 4-in-1 colour ink tank printer with fax, duplex printing and Wi-Fi. Designed for busy offices requiring high-volume, low-cost printing.",
    specs: [
      { label: "Functions", value: "Print, Scan, Copy, Fax" },
      { label: "Print Speed", value: "17/16 ipm (Mono/Colour)" },
      { label: "Print Resolution", value: "1,200 x 6,000 dpi" },
      { label: "ADF Capacity", value: "20 Sheets A4" },
      { label: "Paper Tray", value: "150 Sheets A4" },
      { label: "Duplex", value: "Yes" },
      { label: "Connectivity", value: "USB 2.0, Wireless, Wi-Fi Direct" },
      { label: "Display", value: '1.8" Color LCD' },
      { label: "Memory", value: "128 MB" },
      { label: "Dimensions", value: "435 × 418 × 180 mm (9.4 kg)" },
    ],
    isFeatured: true,
    isNew: true,
    inStock: true,
    images: ["/products/mfc-t930dw.jpg"],
  },
  {
    id: "dcp-t830dw",
    name: "DCP-T830DW Brother 3-in-1 Ink Tank A4 Printer",
    slug: "dcp-t830dw",
    categorySlug: "printers-mfp",
    categoryName: "Printers & MFP",
    brand: "Brother",
    price: 99.0,
    description:
      "Efficient 3-in-1 ink tank printer offering high-yield, low-cost printing with wireless connectivity and duplex printing.",
    specs: [
      { label: "Functions", value: "Print, Scan, Copy" },
      { label: "Print Speed", value: "17/16 ipm (Mono/Colour)" },
      { label: "Print Resolution", value: "1,200 x 6,000 dpi" },
      { label: "ADF Capacity", value: "20 Sheets A4" },
      { label: "Paper Tray", value: "150 Sheets A4" },
      { label: "Duplex", value: "Yes" },
      { label: "Connectivity", value: "USB 2.0, Wireless, Wi-Fi Direct" },
      { label: "Display", value: "1-Line LCD" },
      { label: "Memory", value: "128 MB" },
    ],
    isFeatured: false,
    isNew: true,
    inStock: true,
    images: ["/products/dcp-t830dw.png"],
  },
  {
    id: "hl-l6210dw",
    name: "HL-L6210DW Brother Mono Laser Printer",
    slug: "hl-l6210dw",
    categorySlug: "printers-mfp",
    categoryName: "Printers & MFP",
    brand: "Brother",
    price: 85.0,
    description:
      "High-speed mono laser printer delivering 50 ppm with automatic duplex and 1 GB memory for demanding workgroups.",
    specs: [
      { label: "Function", value: "Printer Only" },
      { label: "Print Speed", value: "50 ppm A4" },
      { label: "Print Resolution", value: "1,200 x 1,200 dpi" },
      { label: "Duplex", value: "Yes, 24 ppm A4" },
      { label: "Connectivity", value: "Wi-Fi Direct, Wired/Wireless, USB 2.0" },
      { label: "Display", value: "1-Line LCD" },
      { label: "Memory", value: "1 GB" },
      { label: "Paper Capacity", value: "520 Sheets A4" },
    ],
    isFeatured: true,
    isNew: true,
    inStock: true,
    images: ["/products/hl-l6210dw.png"],
  },
  {
    id: "hl-l5210dw",
    name: "HL-L5210DW Brother Mono Laser Printer",
    slug: "hl-l5210dw",
    categorySlug: "printers-mfp",
    categoryName: "Printers & MFP",
    brand: "Brother",
    price: 80.0,
    description:
      "Professional mono laser printer with 48 ppm print speed, duplex and 512 MB memory for high-volume printing.",
    specs: [
      { label: "Function", value: "Printer Only" },
      { label: "Print Speed", value: "48 ppm A4" },
      { label: "Print Resolution", value: "1,200 x 1,200 dpi" },
      { label: "Duplex", value: "Yes" },
      { label: "Connectivity", value: "Wi-Fi Direct, Wired/Wireless, USB 2.0" },
      { label: "Display", value: "1-Line LCD" },
      { label: "Memory", value: "512 MB" },
      { label: "Paper Capacity", value: "250 Sheets A4" },
    ],
    isComingSoon: true,
    inStock: false,
  },
  {
    id: "hl-l2461dw",
    name: "HL-L2461DW Brother Mono Laser Printer",
    slug: "hl-l2461dw",
    categorySlug: "printers-mfp",
    categoryName: "Printers & MFP",
    brand: "Brother",
    price: 42.0,
    description:
      "Compact mono laser printer ideal for small offices. Features 34 ppm print speed, automatic duplex and wireless connectivity.",
    specs: [
      { label: "Function", value: "Printer Only" },
      { label: "Print Speed", value: "34/36 ppm (A4/LTR)" },
      { label: "Print Resolution", value: "1,200 x 1,200 dpi" },
      { label: "Duplex", value: "Yes" },
      { label: "Connectivity", value: "Wi-Fi Direct, Wired/Wireless, USB 2.0" },
      { label: "Display", value: "1-Line LCD (16 characters)" },
      { label: "Memory", value: "64 MB" },
      { label: "Paper Capacity", value: "250 Sheets A4" },
    ],
    isFeatured: true,
    inStock: true,
    images: ["/products/hl-l2461dw.jpeg"],
  },
  {
    id: "mfc-l8390cdw",
    name: "MFC-L8390CDW Brother Color Laser Multifunction Printer 4-in-1",
    slug: "mfc-l8390cdw",
    categorySlug: "printers-mfp",
    categoryName: "Printers & MFP",
    brand: "Brother",
    price: 155.0,
    description:
      "Enterprise-grade colour laser MFP with 30 ppm speed, 50-sheet ADF, NFC reader and 3.5-inch colour touchscreen.",
    specs: [
      { label: "Functions", value: "Print, Scan, Copy, Fax" },
      { label: "Print Speed", value: "Up to 30 ppm" },
      { label: "ADF Capacity", value: "50 Sheets A4" },
      { label: "Duplex", value: "Yes" },
      { label: "Paper Tray", value: "250 Sheets A4" },
      { label: "Scan", value: "Dual CIS Color Scan" },
      { label: "Connectivity", value: "Wi-Fi Direct, Wireless, Wired, NFC" },
      { label: "Memory", value: "512 MB" },
      { label: "Display", value: '3.5" Color Touchscreen' },
    ],
    isFeatured: true,
    isNew: true,
    inStock: true,
    images: ["/products/mfc-l8390cdw.jpg"],
  },

  // ── Label Printers ──────────────────────────────────────────────────────────
  {
    id: "ql820nwb",
    name: "QL-820NWB Brother Wireless Thermal Label Printer",
    slug: "ql820nwb",
    categorySlug: "label-printers",
    categoryName: "Label Printers",
    brand: "Brother",
    price: 105.0,
    description:
      "Advanced wireless label printer supporting USB, Ethernet, Wi-Fi and Bluetooth. Prints labels up to 62 mm with black/red printing capability.",
    specs: [
      { label: "Max Label Width", value: "62 mm" },
      { label: "Connectivity", value: "USB, Ethernet, Wi-Fi, Bluetooth" },
      { label: "Display", value: "Backlit LCD" },
      { label: "Special Feature", value: "Black & Red Printing, Timestamp" },
      { label: "Mobile Printing", value: "AirPrint, iOS & Android" },
    ],
    isFeatured: true,
    isNew: true,
    inStock: true,
    images: ["/products/ql820nwb.jpg"],
  },
  {
    id: "pt-d460bt",
    name: "PT-D460BT Brother Label Printer with PC & Bluetooth",
    slug: "pt-d460bt",
    categorySlug: "label-printers",
    categoryName: "Label Printers",
    brand: "Brother",
    price: 39.0,
    description:
      "Versatile label printer with Bluetooth and USB connectivity. Supports Arabic, English and Farsi with QWERTY keyboard.",
    specs: [
      { label: "Max Tape Width", value: "Up to 18 mm TZe" },
      { label: "Languages", value: "Arabic, English, Farsi" },
      { label: "Cutter", value: "Manual" },
      { label: "Print Speed", value: "Up to 30 mm/s" },
      { label: "Resolution", value: "180 dpi" },
      { label: "Connectivity", value: "USB, Bluetooth" },
      { label: "Keyboard", value: "QWERTY" },
    ],
    isFeatured: true,
    isNew: true,
    inStock: true,
    images: ["/products/pt-d460bt.jpg"],
  },
  {
    id: "pt-d450",
    name: "PT-D450 Brother Label Printer – Up to 18mm / PC Connectivity",
    slug: "pt-d450",
    categorySlug: "label-printers",
    categoryName: "Label Printers",
    brand: "Brother",
    price: 25.0,
    comparePrice: 54.0,
    description:
      "Compact label printer with PC connectivity. Create professional labels for cables, shelves and files up to 18 mm wide.",
    specs: [
      { label: "Product Type", value: "Label Printer" },
      { label: "Printing Size", value: "Up to 18 mm" },
      { label: "Print Resolution", value: "180 dpi" },
      { label: "Print Speed", value: "Up to 20 mm/s" },
    ],
    isFeatured: true,
    inStock: true,
    images: ["/products/pt-d450.png"],
  },
  {
    id: "pt-e560btvp",
    name: "PT-E560BTVP Brother Industrial Label Printer",
    slug: "pt-e560btvp",
    categorySlug: "label-printers",
    categoryName: "Label Printers",
    brand: "Brother",
    price: 96.0,
    description:
      "Industrial-grade label printer for electrical, network and facility management labelling. Supports heat-shrink tubing and multiple tape widths.",
    specs: [
      { label: "Tape Widths", value: "6, 9, 12, 18, 24 mm" },
      { label: "Keyboard", value: "QWERTY" },
      { label: "Display", value: "18 characters × 3 lines" },
      { label: "Media", value: "TZe, HGe, HSe (Heat-Shrink Tube)" },
      { label: "Print Speed", value: "30 mm/s" },
      { label: "Resolution", value: "180 dpi / 128 dot" },
      { label: "Barcodes", value: "11 types incl. QR Code" },
      { label: "Connectivity", value: "USB 2.0, Bluetooth 5.0" },
      { label: "Cutter", value: "Auto (Full & Half)" },
      { label: "Weight", value: "1.05 kg" },
    ],
    isFeatured: false,
    inStock: true,
    images: ["/products/pt-e560btvp.jpg"],
  },

  // ── Inks & Toners ──────────────────────────────────────────────────────────
  {
    id: "btd60bk",
    name: "BTD60BK Brother Black Ink Tank",
    slug: "btd60bk",
    categorySlug: "inks-toners",
    categoryName: "Inks & Toners",
    brand: "Brother",
    price: 3.0,
    description:
      "High-yield black ink tank with approximately 7,500 pages. Compatible with Brother DCP-T and MFC-T series ink tank printers.",
    specs: [
      { label: "Colour", value: "Black" },
      { label: "Page Yield", value: "Approx. 7,500 pages" },
      {
        label: "Compatible With",
        value:
          "DCP-T220, DCP-T420W, DCP-T520W, DCP-T720DW, DCP-T820DW, MFC-T920DW, HL-T4000DW, MFC-T4500DW, DCP-T300, DCP-T500W, DCP-T700DW, DCP-T800DW",
      },
    ],
    isFeatured: false,
    inStock: true,
    images: ["/products/btd60bk.jpg"],
  },
  {
    id: "btd100bk",
    name: "BTD100BK Brother Black Ink Bottle",
    slug: "btd100bk",
    categorySlug: "inks-toners",
    categoryName: "Inks & Toners",
    brand: "Brother",
    price: 3.0,
    description:
      "Black ink bottle with approximately 6,000 pages. For use with DCP-T430W, DCP-T530DW, DCP-T730DW and related models.",
    specs: [
      { label: "Colour", value: "Black" },
      { label: "Page Yield", value: "Approx. 6,000 pages" },
      {
        label: "Compatible With",
        value: "DCP-T430W, DCP-T530DW, DCP-T730DW, DCP-T830DW, MFC-T930DW",
      },
    ],
    inStock: true,
    images: ["/products/btd100bk.jpg"],
  },
  {
    id: "btd100y",
    name: "BTD100Y Brother Yellow Ink Bottle",
    slug: "btd100y",
    categorySlug: "inks-toners",
    categoryName: "Inks & Toners",
    brand: "Brother",
    price: 3.0,
    description: "Yellow ink bottle, approx. 5,000 pages.",
    specs: [
      { label: "Colour", value: "Yellow" },
      { label: "Page Yield", value: "Approx. 5,000 pages" },
      {
        label: "Compatible With",
        value: "DCP-T430W, DCP-T530DW, DCP-T730DW, DCP-T830DW, MFC-T930DW",
      },
    ],
    inStock: true,
    images: ["/products/btd100y.jpg"],
  },
  {
    id: "btd100m",
    name: "BTD100M Brother Magenta Ink Bottle",
    slug: "btd100m",
    categorySlug: "inks-toners",
    categoryName: "Inks & Toners",
    brand: "Brother",
    price: 3.0,
    description: "Magenta ink bottle, approx. 5,000 pages.",
    specs: [
      { label: "Colour", value: "Magenta" },
      { label: "Page Yield", value: "Approx. 5,000 pages" },
      {
        label: "Compatible With",
        value: "DCP-T430W, DCP-T530DW, DCP-T730DW, DCP-T830DW, MFC-T930DW",
      },
    ],
    inStock: true,
    images: ["/products/btd100m.jpg"],
  },
  {
    id: "bt5000y",
    name: "BT5000Y Brother Yellow Ink Tank",
    slug: "bt5000y",
    categorySlug: "inks-toners",
    categoryName: "Inks & Toners",
    brand: "Brother",
    price: 3.0,
    description: "Yellow ink tank, approx. 5,000 pages.",
    specs: [
      { label: "Colour", value: "Yellow" },
      { label: "Page Yield", value: "Approx. 5,000 pages" },
    ],
    inStock: true,
    images: ["/products/bt5000y.jpg"],
  },
  {
    id: "bt5000m",
    name: "BT5000M Brother Magenta Ink Tank",
    slug: "bt5000m",
    categorySlug: "inks-toners",
    categoryName: "Inks & Toners",
    brand: "Brother",
    price: 3.0,
    description: "Magenta ink tank, approx. 5,000 pages.",
    specs: [{ label: "Colour", value: "Magenta" }],
    inStock: true,
    images: ["/products/bt5000m.jpg"],
  },
  {
    id: "bt5000c",
    name: "BT5000C Brother Cyan Ink Tank",
    slug: "bt5000c",
    categorySlug: "inks-toners",
    categoryName: "Inks & Toners",
    brand: "Brother",
    price: 3.0,
    description: "Cyan ink tank, approx. 5,000 pages.",
    specs: [{ label: "Colour", value: "Cyan" }],
    inStock: true,
    images: ["/products/bt5000c.jpg"],
  },
  {
    id: "lc3717bk",
    name: "LC3717BK Brother Black Ink Cartridge",
    slug: "lc3717bk",
    categorySlug: "inks-toners",
    categoryName: "Inks & Toners",
    brand: "Brother",
    price: 4.75,
    description: "Black ink cartridge, approx. 550 pages A4 normal yield.",
    specs: [
      { label: "Colour", value: "Black" },
      { label: "Page Yield", value: "Approx. 550 pages A4" },
    ],
    inStock: true,
    images: ["/products/lc3717bk.jpg"],
  },
  {
    id: "lc3717c",
    name: "LC3717C Brother Cyan Ink Cartridge",
    slug: "lc3717c",
    categorySlug: "inks-toners",
    categoryName: "Inks & Toners",
    brand: "Brother",
    price: 3.75,
    description: "Cyan ink cartridge, approx. 550 pages A4 normal yield.",
    specs: [{ label: "Colour", value: "Cyan" }],
    inStock: true,
    images: ["/products/lc3717c.jpg"],
  },
  {
    id: "lc3717y",
    name: "LC3717Y Brother Yellow Ink Cartridge",
    slug: "lc3717y",
    categorySlug: "inks-toners",
    categoryName: "Inks & Toners",
    brand: "Brother",
    price: 3.75,
    description: "Yellow ink cartridge, approx. 550 pages A4 normal yield.",
    specs: [{ label: "Colour", value: "Yellow" }],
    inStock: true,
    images: ["/products/lc3717m.jpg"],
  },
  {
    id: "lc3719xlbk",
    name: "LC3719XLBK Brother Black High-Yield Ink Cartridge",
    slug: "lc3719xlbk",
    categorySlug: "inks-toners",
    categoryName: "Inks & Toners",
    brand: "Brother",
    price: 10.0,
    description: "High-yield black ink cartridge, approx. 3,000 pages A4.",
    specs: [
      { label: "Colour", value: "Black" },
      { label: "Page Yield", value: "Approx. 3,000 pages A4" },
    ],
    inStock: true,
    images: ["/products/lc3719xlbk.jpg"],
  },
  {
    id: "tn279m",
    name: "TN279M Brother Magenta Standard Toner Cartridge",
    slug: "tn279m",
    categorySlug: "inks-toners",
    categoryName: "Inks & Toners",
    brand: "Brother",
    price: 20.0,
    description: "Magenta standard yield toner cartridge, approx. 1,200 pages.",
    specs: [
      { label: "Colour", value: "Magenta" },
      { label: "Page Yield", value: "Approx. 1,200 pages" },
      {
        label: "Compatible With",
        value:
          "HL-L3280CDW, DCP-L3560CDW, MFC-L3760CDW, MFC-L8390CDW, DCP-L3520CDW",
      },
    ],
    inStock: true,
  },
  {
    id: "tn261m",
    name: "TN261M Brother Magenta LaserJet Toner",
    slug: "tn261m",
    categorySlug: "inks-toners",
    categoryName: "Inks & Toners",
    brand: "Brother",
    price: 20.0,
    description: "Magenta toner for LaserJet, approx. 1,400 pages.",
    specs: [
      { label: "Colour", value: "Magenta" },
      { label: "Page Yield", value: "Approx. 1,400 pages" },
      {
        label: "Compatible With",
        value: "HL-3150CDN, HL-3170CDW, MFC-9140CDN, MFC-9330CDW",
      },
    ],
    inStock: true,
  },
  {
    id: "tn2500",
    name: "TN2500 Brother Black Standard Toner Cartridge",
    slug: "tn2500",
    categorySlug: "inks-toners",
    categoryName: "Inks & Toners",
    brand: "Brother",
    price: 12.5,
    description: "Standard-yield black toner, approx. 1,200 pages.",
    specs: [
      { label: "Colour", value: "Black" },
      { label: "Page Yield", value: "Approx. 1,200 pages" },
      {
        label: "Compatible With",
        value:
          "HL-L2461DW, DCP-L2640DW, DCP-L2625DW, MFC-L2805DW, MFC-L2885DW",
      },
    ],
    isNew: true,
    inStock: true,
    images: ["/products/tn261m.jpg"],
  },
  {
    id: "tn2500xl",
    name: "TN2500XL Brother Black High-Yield Toner Cartridge",
    slug: "tn2500xl",
    categorySlug: "inks-toners",
    categoryName: "Inks & Toners",
    brand: "Brother",
    price: 22.0,
    description: "High-yield black toner, approx. 3,000 pages.",
    specs: [
      { label: "Colour", value: "Black" },
      { label: "Page Yield", value: "Approx. 3,000 pages" },
      {
        label: "Compatible With",
        value:
          "HL-L2461DW, DCP-L2640DW, DCP-L2625DW, MFC-L2805DW, MFC-L2885DW",
      },
    ],
    isNew: true,
    inStock: true,
    images: ["/products/lc3719xlbk.jpg"],
  },

  // ── Labels & Tapes ──────────────────────────────────────────────────────────
  {
    id: "dk-22205",
    name: "DK-22205 Brother Continuous Roll – Black on White – 62mm × 30.48M",
    slug: "dk-22205",
    categorySlug: "labels-tapes",
    categoryName: "Labels & Tapes",
    brand: "Brother",
    price: 6.75,
    description:
      "White continuous paper tape 62 mm × 30.48 M. Black on white for QL-series label printers.",
    specs: [
      { label: "Width", value: "62 mm" },
      { label: "Length", value: "30.48 M" },
      { label: "Colour", value: "Black on White" },
      { label: "Material", value: "Paper" },
    ],
    isFeatured: true,
    inStock: true,
    images: ["/products/dk-22205.png"],
  },
  {
    id: "dk-22212",
    name: "DK-22212 Brother Continuous Roll – Black on White – 62mm × 15.24M",
    slug: "dk-22212",
    categorySlug: "labels-tapes",
    categoryName: "Labels & Tapes",
    brand: "Brother",
    price: 20.0,
    description: "White continuous film tape 62 mm × 15.24 M. Black on white.",
    specs: [
      { label: "Width", value: "62 mm" },
      { label: "Length", value: "15.24 M" },
      { label: "Colour", value: "Black on White" },
      { label: "Material", value: "Film" },
    ],
    isNew: true,
    inStock: true,
    images: ["/products/dk-22212.png"],
  },
  {
    id: "dk-22251",
    name: "DK-22251 Brother Adhesive Roll – Black/Red on White – 62mm × 15.24M",
    slug: "dk-22251",
    categorySlug: "labels-tapes",
    categoryName: "Labels & Tapes",
    brand: "Brother",
    price: 9.75,
    description:
      "Adhesive continuous label roll in black/red on white for eye-catching two-colour labels.",
    specs: [
      { label: "Width", value: "62 mm" },
      { label: "Length", value: "15.24 M" },
      { label: "Colour", value: "Black/Red on White" },
    ],
    inStock: true,
    images: ["/products/dk-22251.jpg"],
  },
  {
    id: "tze-231",
    name: "TZe-231 Brother Black on White Tape – 12mm (8m)",
    slug: "tze-231",
    categorySlug: "labels-tapes",
    categoryName: "Labels & Tapes",
    brand: "Brother",
    price: 5.0,
    description: "TZe laminated tape 12 mm wide. Black on white, 8 m roll.",
    specs: [
      { label: "Width", value: "12 mm" },
      { label: "Length", value: "8 m" },
      { label: "Colour", value: "Black on White" },
    ],
    inStock: true,
  },
  {
    id: "tze-251",
    name: "TZe-251 Brother Black on White Tape – 24mm",
    slug: "tze-251",
    categorySlug: "labels-tapes",
    categoryName: "Labels & Tapes",
    brand: "Brother",
    price: 8.25,
    description: "TZe laminated tape 24 mm wide. Black on white.",
    specs: [
      { label: "Width", value: "24 mm" },
      { label: "Colour", value: "Black on White" },
    ],
    inStock: true,
  },
  {
    id: "tze-fx241",
    name: "TZe-FX241 Brother Flexible ID Black on White Tape – 18mm",
    slug: "tze-fx241",
    categorySlug: "labels-tapes",
    categoryName: "Labels & Tapes",
    brand: "Brother",
    price: 8.0,
    description: "Flexible ID laminated tape 18 mm. Ideal for wrapping cables.",
    specs: [
      { label: "Width", value: "18 mm" },
      { label: "Colour", value: "Black on White" },
      { label: "Type", value: "Flexible ID" },
    ],
    inStock: true,
  },

  // ── Scanners ──────────────────────────────────────────────────────────────
  {
    id: "ads1300",
    name: "ADS-1300 Brother Document Scanner",
    slug: "ads1300",
    categorySlug: "scanners",
    categoryName: "Scanners",
    brand: "Brother",
    price: 85.0,
    description:
      "Compact document scanner with 30 ppm A4 speed, 60 ipm duplex scan, and plastic ID card slot.",
    specs: [
      { label: "Scan Speed", value: "Up to 30 ppm A4" },
      { label: "Duplex Scan", value: "Up to 60 ipm" },
      { label: "ADF Capacity", value: "20 Sheets" },
      { label: "Special Features", value: "Plastic ID Card Slot" },
      { label: "Scan To", value: "PC, Cloud, USB" },
      { label: "Resolution", value: "600 × 600 dpi" },
    ],
    isFeatured: true,
    isNew: true,
    inStock: true,
    images: ["/products/ads1300.jpg"],
  },

  // ── Shredders ──────────────────────────────────────────────────────────────
  {
    id: "jinpex-mr2814md",
    name: "Jinpex Shredder MR-2814MD",
    slug: "jinpex-mr2814md",
    categorySlug: "shredders",
    categoryName: "Shredders",
    brand: "Jinpex",
    price: 69.0,
    description:
      "P5 security micro-cut shredder for offices. Shreds paper, credit cards, staples and paper clips into 2 × 10 mm particles.",
    specs: [
      { label: "Cut Type", value: "Micro Cut" },
      { label: "Cut Size", value: "2 × 10 mm" },
      { label: "Capacity", value: "14 sheets (70 g)" },
      { label: "Cut Speed", value: "2.5 m/min" },
      { label: "Throat Width", value: "230 mm" },
      { label: "Shreds", value: "Paper, Credit Cards, Staples, Paper Clips" },
      { label: "Security Level", value: "P5" },
      { label: "Noise Level", value: "< 52 dB" },
      { label: "Bin Capacity", value: "30 L" },
      { label: "Dimensions (LxWxH)", value: "410 × 280 × 603 mm" },
      { label: "Weight", value: "18.3 kg" },
      { label: "Auto Start/Stop", value: "Yes" },
    ],
    isFeatured: true,
    inStock: true,
    images: ["/products/jinpex-shredder.jpg"],
  },
  {
    id: "jinpex-mr4020md",
    name: "Jinpex Shredder MR-4020MD",
    slug: "jinpex-mr4020md",
    categorySlug: "shredders",
    categoryName: "Shredders",
    brand: "Jinpex",
    price: 144.0,
    description:
      "Heavy-duty micro-cut shredder for larger offices. 20-sheet capacity, 40 L bin.",
    specs: [
      { label: "Cut Type", value: "Micro Cut" },
      { label: "Cut Size", value: "2 × 10 mm" },
      { label: "Capacity", value: "20 sheets (70 g)" },
      { label: "Cut Speed", value: "2.5 m/min" },
      { label: "Security Level", value: "P5" },
      { label: "Bin Capacity", value: "40 L" },
      { label: "Dimensions", value: "460 × 306 × 737 mm" },
      { label: "Weight", value: "24.5 kg" },
      { label: "Auto Start/Stop", value: "Yes" },
    ],
    isNew: true,
    inStock: true,
    images: ["/products/jinpex-shredder.jpg"],
  },
  {
    id: "jinpex-mr2212cd",
    name: "Jinpex Shredder MR-2212CD",
    slug: "jinpex-mr2212cd",
    categorySlug: "shredders",
    categoryName: "Shredders",
    brand: "Jinpex",
    price: 49.0,
    description:
      "P4 cross-cut shredder for personal and small office use. 12-sheet capacity, 22 L bin.",
    specs: [
      { label: "Cut Type", value: "Cross Cut" },
      { label: "Cut Size", value: "4 × 15 mm" },
      { label: "Capacity", value: "12 sheets (70 g)" },
      { label: "Security Level", value: "P4" },
      { label: "Bin Capacity", value: "22 L" },
      { label: "Dimensions", value: "380 × 250 × 517 mm" },
      { label: "Weight", value: "9.1 kg" },
    ],
    inStock: true,
    images: ["/products/jinpex-shredder.jpg"],
  },

  // ── Safes & Filing ────────────────────────────────────────────────────────
  {
    id: "diplomat-cb320",
    name: "Diplomat Safe CB320",
    slug: "diplomat-cb320",
    categorySlug: "safes-filing",
    categoryName: "Safes & Filing",
    brand: "Diplomat",
    price: 19.0,
    description:
      "Portable cash box with combination dial and key lock. Compact design for secure cash storage.",
    specs: [
      { label: "Dimensions (HxWxD)", value: "130 × 320 × 240 mm" },
      { label: "Weight", value: "3.2 kg" },
      { label: "Lock Type", value: "Combination Dial + Key Lock" },
      { label: "Type", value: "Portable Cash Box" },
    ],
    isFeatured: true,
    inStock: true,
    images: ["/products/diplomat-cb320.jpg"],
  },
  {
    id: "diplomat-200ehk",
    name: "Diplomat Safe 200EHK",
    slug: "diplomat-200ehk",
    categorySlug: "safes-filing",
    categoryName: "Safes & Filing",
    brand: "Diplomat",
    price: 445.0,
    description:
      "Fire-resistant large safe with digital + key lock, 3 adjustable shelves and 1 lockable drawer. 120-minute fire rating.",
    specs: [
      { label: "External Dimensions", value: "H1690 × W775 × D690 mm" },
      { label: "Internal Dimensions", value: "H1450 × W595 × D440 mm" },
      { label: "Weight", value: "388 kg" },
      { label: "Capacity", value: "379.6 L" },
      { label: "Shelves", value: "3 Height-Adjustable" },
      { label: "Drawer", value: "1 Lockable Bottom Drawer" },
      { label: "Lock", value: "Digital + Key" },
      { label: "Fire Rating", value: "120 Min Fire Resistant" },
    ],
    isFeatured: true,
    isNew: true,
    inStock: true,
    images: ["/products/diplomat-200ehk.png"],
  },

  // ── Accessories ──────────────────────────────────────────────────────────
  {
    id: "nc-9000w",
    name: "NC-9000W Brother Wi-Fi Adapter Kit",
    slug: "nc-9000w",
    categorySlug: "accessories",
    categoryName: "Accessories",
    brand: "Brother",
    price: 25.0,
    description:
      "Dual-band 2.4/5 GHz Wi-Fi adapter for Brother HL-L9430CDN and MFC-L9630CDN printers.",
    specs: [
      { label: "Type", value: "Wi-Fi Adapter" },
      { label: "Frequency", value: "2.4/5 GHz" },
      {
        label: "Compatible With",
        value: "HL-L9430CDN, MFC-L9630CDN",
      },
    ],
    isNew: true,
    inStock: true,
    images: ["/products/nc-9000w.jpg"],
  },
];

export function getProductsByCategory(categorySlug: string): Product[] {
  return PRODUCTS.filter((p) => p.categorySlug === categorySlug);
}

export function getProductBySlug(
  categorySlug: string,
  productSlug: string
): Product | undefined {
  return PRODUCTS.find(
    (p) => p.categorySlug === categorySlug && p.slug === productSlug
  );
}

export function getFeaturedProducts(limit = 8): Product[] {
  return PRODUCTS.filter((p) => p.isFeatured).slice(0, limit);
}

export function getNewArrivals(limit = 8): Product[] {
  return PRODUCTS.filter((p) => p.isNew).slice(0, limit);
}

export function getBestSellers(limit = 8): Product[] {
  return PRODUCTS.filter((p) => p.isFeatured && !p.isComingSoon).slice(0, limit);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return PRODUCTS.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.categoryName.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q)
  );
}
